### ISSUE TITLE
Usage of hdf5read crashes the instrument at compile time

### ISSUE THREAD

**Issue by idranoels** [csound/plugins#11]
Hello everybody
I’m using Cabbage as a frontend for CSound and I’m trying to user hdf5write/hdf5read to save and restore datas to disk.
In a test file I have a line like this:

```
printks"before hdf5read:\n", 0
;        aArray[], aVar, kVar hdf5read "f:/mypath/src/cabbage/example.h5", "aArray*", "aVar", "kVar" ; Open hdf5 file and read variables
printks"after hdf5read:\n", 0

```
but if I remove the comment Cabbage suddenly crashes without printing anything before, so it should be a compile time issue.
The same issue occurs when I use CSound standalone.

I’m running under the following SW stack:

```
Windows 10
CSound 6.16 (double samples) Jul 17 2021
Cabbage 2.8.0

```
I attach:

CSound instrument [test_3.csd.txt](https://github.com/csound/plugins/files/7958342/test_3.csd.txt)
CSound output [test_3.txt](https://github.com/csound/plugins/files/7958343/test_3.txt)
Windows Event Viewer crash [EventViewer.txt](https://github.com/csound/plugins/files/7958344/EventViewer.txt)

Thank you in advance

Sergio

**Comment by jpffitch** [comment]
I believe this is fixed in GitHub sources.  Only tested on Linux (all I have).

There were multiple problems mainly affecting reading arrays.
