### ISSUE TITLE
Non-configurable install location prevents packaging on Homebrew

### ISSUE THREAD

**Issue by nwhetsell** [csound/plugins#12]
At commit 028c6e8de07dcddd9bd8b4219931a8c30fca48ac, the value of `PLUGIN_INSTALL_DIR` (which determines where plug-ins are installed) was hard-coded to `$HOME/Library/csound/<csound_version>/plugins64` on macOS when Csound uses double-precision samples. This means that plug-ins can’t be installed on macOS using Homebrew, as Homebrew does not permit installing files at that location. Not building Csound plug-ins using Homebrew isn’t really an option, as some Homebrew users rely on these plug-ins being there: https://listserv.heanet.ie/cgi-bin/wa?A1=ind2107&L=CSOUND-DEV#18. Please support a configurable `PLUGIN_INSTALL_DIR`.

**Comment by vlazzarini** [comment]
There is no current maintainer for this repository, but we are happy to take a PR on this.

**Comment by dvzrv** [comment]
@nwhetsell this is not really fixed, as there is no new release yet and downstreams can not package this software.

@vlazzarini A patch level release would be awesome! Thanks! :)

**Comment by nwhetsell** [comment]
@dvzrv I’ll leave reopening this issue to the repository owners; as far as Homebrew is concerned, this is issue is resolved.  Csound plugins are managed using a [`resource` block](https://rubydoc.brew.sh/Formula#resource-class_method) ([here](https://github.com/Homebrew/homebrew-core/blob/20630dc51005c34d39029ac7432a7c82014fdc36/Formula/csound.rb#L60-L63)), for which no release is necessary.

**Comment by vlazzarini** [comment]
@dvzrv there's an open issue with hdr5 opcodes, which is been looked at by John. I can do a source code release once that's cleared.

**Comment by vlazzarini** [comment]
@dvzrv release is done now that the hdrf5 opcodes were fixed

https://github.com/csound/plugins/releases/tag/1.0.2
