### ISSUE TITLE
Jacko hangs because of 'event' 

### ISSUE THREAD

**Issue by tjingboem** [csound/plugins#20]
i came across an issue that prevents me from using the Jacko opcodes making the Jack connections i want.
I want to use the Jacko opcodes in Blue, to use some external hardware synths via Midi. Now, Blue uses an 'event "e"' to tell the playbackhead to stop. As it turns out, Jacko does not like this and Csound does not stop at the designated time.

For this to test, i have attached several thing
1. event.csd - makes Csound crazy
2. Catia_JackConnection.png - showing the Jacko connection
3. Event_CPU.png - showing Csound going nuts
4. Event_NoStop.png - the output form Visual Studio Code, where (illegally) Jacko re-started after the csd has  finished
5. no_event.csd -  leaving out the 'event "e' and all works just fine

Images and csds:
[JackoImages.zip](https://github.com/csound/plugins/files/12916067/JackoImages.zip)
[Jacko_csd.zip](https://github.com/csound/plugins/files/12916095/Jacko_csd.zip)

**Comment by gogins** [comment]
@stekyne or somebody, could you please actually merge my pull request #21 so that @tjingboem can test it?

**Comment by stekyne** [comment]
@tjingboem Did you get a chance to test this? Can we close the issue?

**Comment by tjingboem** [comment]
i'll close the issue, thanks
