### ISSUE TITLE
Plugins are installed to HOME

### ISSUE THREAD

**Issue by dvzrv** [csound/plugins#6]
Hi! When looking into packaging this project for Arch Linux, I realized that [the installation directory for the plugins is hardcoded to the caller's $HOME](https://github.com/csound/plugins/blob/3ca258062ba677c41d2e7fb40db59467f3bccfe7/CMakeLists.txt#L137).
This is rather bad practice in regards to dealing with this in the context of cmake, as it does not allow for any sane override with the usual environment variables such as `DESTDIR`.

The default should always be to adhere to the system location (e.g. /usr/local) and if installing to a user's home is desired, then this should not be the norm, but be an optional feature.

**Comment by vlazzarini** [comment]
it now uses CMAKE_INSTAL_PREFIX as in the Csound library project.
