### ISSUE TITLE
make install path has error

### ISSUE THREAD

**Issue by anton-k** [csound/plugins#7]
`make install` copies plugin so-files to the impossible path. Notice the space in between:

```
 /usr/local/ /usr/local/lib/csound/plugins64-6.0/libfluidOpcodes.so
```

**Comment by vlazzarini** [comment]
The CMakeLists.txt script installs to 

'''
${CMAKE_INSTALL_PREFIX}/lib/csound/plugins64-6.0
'''

or if -DLIB64=1 is used

'''
${CMAKE_INSTALL_PREFIX}/lib/csound/plugins64-6.0
'''

So make sure the `CMAKE_INSTALL_PREFIX` is set to where you want it to be.

**Comment by anton-k** [comment]
Can you please document this. As it's not mentioned in the build instructions

**Comment by anton-k** [comment]
When I follow README it's done not as expected and fails to install the compiled sos

**Comment by vlazzarini** [comment]
If you run cmake -LA you should get all cmake build options.

This is the same as the Csound library build.

**Comment by vlazzarini** [comment]
There was a ticket today asking for it to be changed so I did it. However I am not committing to maintaining this repository. It does not have a maintainer so any requests might be delayed.
