### ISSUE TITLE
no way to configure csound path

### ISSUE THREAD

**Issue by anton-k** [csound/plugins#8]
if csound is not installed in the expected directory there is no way to configure that path.
It's mentioned in the DOCs that there are flags for that but they did not work.

**Comment by vlazzarini** [comment]
There is a way: the CMakeLists.txt script installs to

'''
${CMAKE_INSTALL_PREFIX}/lib/csound/plugins64-6.0
'''

or if -DLIB64=1 is used

'''
${CMAKE_INSTALL_PREFIX}/lib/csound/plugins64-6.0
'''

So make sure the CMAKE_INSTALL_PREFIX is set to where you want it to be.
